# Generated by Django 3.1.6 on 2021-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.TextField(default='none'),
        ),
    ]
