# Generated by Django 3.1.6 on 2021-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210214_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating_count',
            field=models.TextField(default=0),
        ),
    ]
